Codigo MVC/config/routes.rb
Rails.application.routes.draw do
  resources :facultads
  resources :carreras
  resources :semestres
  resources :asignatura_alumnos
  resources :aulas
  resources :horarios
  resources :asignaturas
  resources :alumnos
  resources :profesors
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Codigo MVC/app/models/alumno.rb
class Alumno < ApplicationRecord
  belongs_to :usuario
end

Codigo MVC/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Codigo MVC/app/models/asignatura.rb
class Asignatura < ApplicationRecord
  belongs_to :profesor, optional:true
end

Codigo MVC/app/models/asignatura_alumno.rb
class AsignaturaAlumno < ApplicationRecord
  belongs_to :asignatura
  belongs_to :alumno
end

Codigo MVC/app/models/aula.rb
class Aula < ApplicationRecord
  belongs_to :horario
end

Codigo MVC/app/models/carrera.rb
class Carrera < ApplicationRecord
  belongs_to :semestre
end

Codigo MVC/app/models/facultad.rb
class Facultad < ApplicationRecord
  belongs_to :carrera
end

Codigo MVC/app/models/horario.rb
class Horario < ApplicationRecord
  belongs_to :asignatura
end

Codigo MVC/app/models/profesor.rb
class Profesor < ApplicationRecord
  belongs_to :usuario
end

Codigo MVC/app/models/semestre.rb
class Semestre < ApplicationRecord
  belongs_to :asignatura
end

Codigo MVC/app/models/usuario.rb
class Usuario < ApplicationRecord
end

Codigo MVC/app/controllers/aulas_controller.rb
class AulasController < ApplicationController
  before_action :set_aula, only: [:show, :edit, :update, :destroy]

  # GET /aulas
  # GET /aulas.json
  def index
    @aulas = Aula.all
  end

  # GET /aulas/1
  # GET /aulas/1.json
  def show
  end

  # GET /aulas/new
  def new
    @aula = Aula.new
  end

  # GET /aulas/1/edit
  def edit
  end

  # POST /aulas
  # POST /aulas.json
  def create
    @aula = Aula.new(aula_params)

    respond_to do |format|
      if @aula.save
        format.html { redirect_to @aula, notice: 'Aula was successfully created.' }
        format.json { render :show, status: :created, location: @aula }
      else
        format.html { render :new }
        format.json { render json: @aula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aulas/1
  # PATCH/PUT /aulas/1.json
  def update
    respond_to do |format|
      if @aula.update(aula_params)
        format.html { redirect_to @aula, notice: 'Aula was successfully updated.' }
        format.json { render :show, status: :ok, location: @aula }
      else
        format.html { render :edit }
        format.json { render json: @aula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aulas/1
  # DELETE /aulas/1.json
  def destroy
    @aula.destroy
    respond_to do |format|
      format.html { redirect_to aulas_url, notice: 'Aula was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aula
      @aula = Aula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aula_params
      params.require(:aula).permit(:numero, :nombre, :horario_id)
    end
end

Codigo MVC/app/controllers/horarios_controller.rb
class HorariosController < ApplicationController
  before_action :set_horario, only: [:show, :edit, :update, :destroy]

  # GET /horarios
  # GET /horarios.json
  def index
    @horarios = Horario.all
  end

  # GET /horarios/1
  # GET /horarios/1.json
  def show
  end

  # GET /horarios/new
  def new
    @horario = Horario.new
  end

  # GET /horarios/1/edit
  def edit
  end

  # POST /horarios
  # POST /horarios.json
  def create
    @horario = Horario.new(horario_params)

    respond_to do |format|
      if @horario.save
        format.html { redirect_to @horario, notice: 'Horario was successfully created.' }
        format.json { render :show, status: :created, location: @horario }
      else
        format.html { render :new }
        format.json { render json: @horario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horarios/1
  # PATCH/PUT /horarios/1.json
  def update
    respond_to do |format|
      if @horario.update(horario_params)
        format.html { redirect_to @horario, notice: 'Horario was successfully updated.' }
        format.json { render :show, status: :ok, location: @horario }
      else
        format.html { render :edit }
        format.json { render json: @horario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /horarios/1
  # DELETE /horarios/1.json
  def destroy
    @horario.destroy
    respond_to do |format|
      format.html { redirect_to horarios_url, notice: 'Horario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horario
      @horario = Horario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def horario_params
      params.require(:horario).permit(:bloque, :asignatura_id)
    end
end

Codigo MVC/app/helpers/alumnos_helper.rb
module AlumnosHelper
end

Codigo MVC/app/helpers/application_helper.rb
module ApplicationHelper
end

Codigo MVC/app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

Codigo MVC/app/helpers/aulas_helper.rb
module AulasHelper
end

Codigo MVC/app/helpers/carreras_helper.rb
module CarrerasHelper
end

Codigo MVC/app/helpers/facultads_helper.rb
module FacultadsHelper
end

Codigo MVC/app/helpers/horarios_helper.rb
module HorariosHelper
end

Codigo MVC/app/helpers/profesors_helper.rb
module ProfesorsHelper
end

Codigo MVC/app/helpers/semestres_helper.rb
module SemestresHelper
end

Codigo MVC/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

Codigo MVC/app/views/horarios/_form.html.erb
<%= form_with(model: horario, local: true) do |form| %>
  <% if horario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(horario.errors.count, "error") %> prohibited this horario from being saved:</h2>

      <ul>
      <% horario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bloque %>
    <%= form.number_field :bloque %>
  </div>

  <div class="field">
    <%= form.label :asignatura_id %>
    <%= form.text_field :asignatura_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Codigo MVC/app/views/horarios/edit.html.erb
<h1>Editing Horario</h1>

<%= render 'form', horario: @horario %>

<%= link_to 'Show', @horario %> |
<%= link_to 'Back', horarios_path %>

Codigo MVC/app/views/horarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Horarios</h1>

<table>
  <thead>
    <tr>
      <th>Bloque</th>
      <th>Asignatura</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @horarios.each do |horario| %>
      <tr>
        <td><%= horario.bloque %></td>
        <td><%= horario.asignatura %></td>
        <td><%= link_to 'Show', horario %></td>
        <td><%= link_to 'Edit', edit_horario_path(horario) %></td>
        <td><%= link_to 'Destroy', horario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Horario', new_horario_path %>

Codigo MVC/app/views/horarios/new.html.erb
<h1>New Horario</h1>

<%= render 'form', horario: @horario %>

<%= link_to 'Back', horarios_path %>

Codigo MVC/app/views/horarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bloque:</strong>
  <%= @horario.bloque %>
</p>

<p>
  <strong>Asignatura:</strong>
  <%= @horario.asignatura %>
</p>

<%= link_to 'Edit', edit_horario_path(@horario) %> |
<%= link_to 'Back', horarios_path %>