Codigo MVC/config/routes.rb
Rails.application.routes.draw do
  resources :facultads
  resources :carreras
  resources :semestres
  resources :asignatura_alumnos
  resources :aulas
  resources :horarios
  resources :asignaturas
  resources :alumnos
  resources :profesors
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Codigo MVC/app/models/alumno.rb
class Alumno < ApplicationRecord
  belongs_to :usuario
end

Codigo MVC/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Codigo MVC/app/models/asignatura.rb
class Asignatura < ApplicationRecord
  belongs_to :profesor, optional:true
end

Codigo MVC/app/models/asignatura_alumno.rb
class AsignaturaAlumno < ApplicationRecord
  belongs_to :asignatura
  belongs_to :alumno
end

Codigo MVC/app/models/aula.rb
class Aula < ApplicationRecord
  belongs_to :horario
end

Codigo MVC/app/models/carrera.rb
class Carrera < ApplicationRecord
  belongs_to :semestre
end

Codigo MVC/app/models/facultad.rb
class Facultad < ApplicationRecord
  belongs_to :carrera
end

Codigo MVC/app/models/horario.rb
class Horario < ApplicationRecord
  belongs_to :asignatura
end

Codigo MVC/app/models/profesor.rb
class Profesor < ApplicationRecord
  belongs_to :usuario
end

Codigo MVC/app/models/semestre.rb
class Semestre < ApplicationRecord
  belongs_to :asignatura
end

Codigo MVC/app/models/usuario.rb
class Usuario < ApplicationRecord
end

Codigo MVC/app/controllers/asignatura_alumnos_controller.rb
class AsignaturaAlumnosController < ApplicationController
  before_action :set_asignatura_alumno, only: [:show, :edit, :update, :destroy]

  # GET /asignatura_alumnos
  # GET /asignatura_alumnos.json
  def index
    @asignatura_alumnos = AsignaturaAlumno.all
  end

  # GET /asignatura_alumnos/1
  # GET /asignatura_alumnos/1.json
  def show
  end

  # GET /asignatura_alumnos/new
  def new
    @asignatura_alumno = AsignaturaAlumno.new
  end

  # GET /asignatura_alumnos/1/edit
  def edit
  end

  # POST /asignatura_alumnos
  # POST /asignatura_alumnos.json
  def create
    @asignatura_alumno = AsignaturaAlumno.new(asignatura_alumno_params)

    respond_to do |format|
      if @asignatura_alumno.save
        format.html { redirect_to @asignatura_alumno, notice: 'Asignatura alumno was successfully created.' }
        format.json { render :show, status: :created, location: @asignatura_alumno }
      else
        format.html { render :new }
        format.json { render json: @asignatura_alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asignatura_alumnos/1
  # PATCH/PUT /asignatura_alumnos/1.json
  def update
    respond_to do |format|
      if @asignatura_alumno.update(asignatura_alumno_params)
        format.html { redirect_to @asignatura_alumno, notice: 'Asignatura alumno was successfully updated.' }
        format.json { render :show, status: :ok, location: @asignatura_alumno }
      else
        format.html { render :edit }
        format.json { render json: @asignatura_alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asignatura_alumnos/1
  # DELETE /asignatura_alumnos/1.json
  def destroy
    @asignatura_alumno.destroy
    respond_to do |format|
      format.html { redirect_to asignatura_alumnos_url, notice: 'Asignatura alumno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asignatura_alumno
      @asignatura_alumno = AsignaturaAlumno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asignatura_alumno_params
      params.require(:asignatura_alumno).permit(:nota, :ponderacion, :asignatura_id, :alumno_id)
    end
end

Codigo MVC/app/helpers/alumnos_helper.rb
module AlumnosHelper
end

Codigo MVC/app/helpers/application_helper.rb
module ApplicationHelper
end

Codigo MVC/app/helpers/asignatura_alumnos_helper.rb
module AsignaturaAlumnosHelper
end

Codigo MVC/app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

Codigo MVC/app/helpers/aulas_helper.rb
module AulasHelper
end

Codigo MVC/app/helpers/carreras_helper.rb
module CarrerasHelper
end

Codigo MVC/app/helpers/facultads_helper.rb
module FacultadsHelper
end

Codigo MVC/app/helpers/horarios_helper.rb
module HorariosHelper
end

Codigo MVC/app/helpers/profesors_helper.rb
module ProfesorsHelper
end

Codigo MVC/app/helpers/semestres_helper.rb
module SemestresHelper
end

Codigo MVC/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

Codigo MVC/app/views/asignatura_alumnos/_form.html.erb
<%= form_with(model: asignatura_alumno, local: true) do |form| %>
  <% if asignatura_alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asignatura_alumno.errors.count, "error") %> prohibited this asignatura_alumno from being saved:</h2>

      <ul>
      <% asignatura_alumno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nota %>
    <%= form.number_field :nota %>
  </div>

  <div class="field">
    <%= form.label :ponderacion %>
    <%= form.number_field :ponderacion %>
  </div>

  <div class="field">
    <%= form.label :asignatura_id %>
    <%= form.text_field :asignatura_id %>
  </div>

  <div class="field">
    <%= form.label :alumno_id %>
    <%= form.text_field :alumno_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Codigo MVC/app/views/asignatura_alumnos/edit.html.erb
<h1>Editing Asignatura Alumno</h1>

<%= render 'form', asignatura_alumno: @asignatura_alumno %>

<%= link_to 'Show', @asignatura_alumno %> |
<%= link_to 'Back', asignatura_alumnos_path %>

Codigo MVC/app/views/asignatura_alumnos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Asignatura Alumnos</h1>

<table>
  <thead>
    <tr>
      <th>Nota</th>
      <th>Ponderacion</th>
      <th>Asignatura</th>
      <th>Alumno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @asignatura_alumnos.each do |asignatura_alumno| %>
      <tr>
        <td><%= asignatura_alumno.nota %></td>
        <td><%= asignatura_alumno.ponderacion %></td>
        <td><%= asignatura_alumno.asignatura %></td>
        <td><%= asignatura_alumno.alumno %></td>
        <td><%= link_to 'Show', asignatura_alumno %></td>
        <td><%= link_to 'Edit', edit_asignatura_alumno_path(asignatura_alumno) %></td>
        <td><%= link_to 'Destroy', asignatura_alumno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asignatura Alumno', new_asignatura_alumno_path %>

Codigo MVC/app/views/asignatura_alumnos/new.html.erb
<h1>New Asignatura Alumno</h1>

<%= render 'form', asignatura_alumno: @asignatura_alumno %>

<%= link_to 'Back', asignatura_alumnos_path %>

Codigo MVC/app/views/asignatura_alumnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nota:</strong>
  <%= @asignatura_alumno.nota %>
</p>

<p>
  <strong>Ponderacion:</strong>
  <%= @asignatura_alumno.ponderacion %>
</p>

<p>
  <strong>Asignatura:</strong>
  <%= @asignatura_alumno.asignatura %>
</p>

<p>
  <strong>Alumno:</strong>
  <%= @asignatura_alumno.alumno %>
</p>

<%= link_to 'Edit', edit_asignatura_alumno_path(@asignatura_alumno) %> |
<%= link_to 'Back', asignatura_alumnos_path %>