Codigo MVC/config/routes.rb
Rails.application.routes.draw do
  resources :facultads
  resources :carreras
  resources :semestres
  resources :asignatura_alumnos
  resources :aulas
  resources :horarios
  resources :asignaturas
  resources :alumnos
  resources :profesors
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Codigo MVC/app/models/alumno.rb
class Alumno < ApplicationRecord
  belongs_to :usuario
end

Codigo MVC/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Codigo MVC/app/models/asignatura.rb
class Asignatura < ApplicationRecord
  belongs_to :profesor, optional:true
end

Codigo MVC/app/models/asignatura_alumno.rb
class AsignaturaAlumno < ApplicationRecord
  belongs_to :asignatura
  belongs_to :alumno
end

Codigo MVC/app/models/aula.rb
class Aula < ApplicationRecord
  belongs_to :horario
end

Codigo MVC/app/models/carrera.rb
class Carrera < ApplicationRecord
  belongs_to :semestre
end

Codigo MVC/app/models/facultad.rb
class Facultad < ApplicationRecord
  belongs_to :carrera
end

Codigo MVC/app/models/horario.rb
class Horario < ApplicationRecord
  belongs_to :asignatura
end

Codigo MVC/app/models/profesor.rb
class Profesor < ApplicationRecord
  belongs_to :usuario
end

Codigo MVC/app/models/semestre.rb
class Semestre < ApplicationRecord
  belongs_to :asignatura
end

Codigo MVC/app/models/usuario.rb
class Usuario < ApplicationRecord
end

Codigo MVC/app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  before_action :set_alumno, only: [:show, :edit, :update, :destroy]

  # GET /alumnos
  # GET /alumnos.json
  def index
    @alumnos = Alumno.all
  end

  # GET /alumnos/1
  # GET /alumnos/1.json
  def show
  end

  # GET /alumnos/new
  def new
    @alumno = Alumno.new
  end

  # GET /alumnos/1/edit
  def edit
  end

  # POST /alumnos
  # POST /alumnos.json
  def create
    @alumno = Alumno.new(alumno_params)

    respond_to do |format|
      if @alumno.save
        format.html { redirect_to @alumno, notice: 'Alumno was successfully created.' }
        format.json { render :show, status: :created, location: @alumno }
      else
        format.html { render :new }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnos/1
  # PATCH/PUT /alumnos/1.json
  def update
    respond_to do |format|
      if @alumno.update(alumno_params)
        format.html { redirect_to @alumno, notice: 'Alumno was successfully updated.' }
        format.json { render :show, status: :ok, location: @alumno }
      else
        format.html { render :edit }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1
  # DELETE /alumnos/1.json
  def destroy
    @alumno.destroy
    respond_to do |format|
      format.html { redirect_to alumnos_url, notice: 'Alumno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno
      @alumno = Alumno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumno_params
      params.require(:alumno).permit(:usuario_id)
    end
end

Codigo MVC/app/controllers/aulas_controller.rb
class AulasController < ApplicationController
  before_action :set_aula, only: [:show, :edit, :update, :destroy]

  # GET /aulas
  # GET /aulas.json
  def index
    @aulas = Aula.all
  end

  # GET /aulas/1
  # GET /aulas/1.json
  def show
  end

  # GET /aulas/new
  def new
    @aula = Aula.new
  end

  # GET /aulas/1/edit
  def edit
  end

  # POST /aulas
  # POST /aulas.json
  def create
    @aula = Aula.new(aula_params)

    respond_to do |format|
      if @aula.save
        format.html { redirect_to @aula, notice: 'Aula was successfully created.' }
        format.json { render :show, status: :created, location: @aula }
      else
        format.html { render :new }
        format.json { render json: @aula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aulas/1
  # PATCH/PUT /aulas/1.json
  def update
    respond_to do |format|
      if @aula.update(aula_params)
        format.html { redirect_to @aula, notice: 'Aula was successfully updated.' }
        format.json { render :show, status: :ok, location: @aula }
      else
        format.html { render :edit }
        format.json { render json: @aula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aulas/1
  # DELETE /aulas/1.json
  def destroy
    @aula.destroy
    respond_to do |format|
      format.html { redirect_to aulas_url, notice: 'Aula was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aula
      @aula = Aula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aula_params
      params.require(:aula).permit(:numero, :nombre, :horario_id)
    end
end

Codigo MVC/app/helpers/alumnos_helper.rb
module AlumnosHelper
end

Codigo MVC/app/helpers/application_helper.rb
module ApplicationHelper
end

Codigo MVC/app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

Codigo MVC/app/helpers/aulas_helper.rb
module AulasHelper
end

Codigo MVC/app/helpers/carreras_helper.rb
module CarrerasHelper
end

Codigo MVC/app/helpers/facultads_helper.rb
module FacultadsHelper
end

Codigo MVC/app/helpers/horarios_helper.rb
module HorariosHelper
end

Codigo MVC/app/helpers/profesors_helper.rb
module ProfesorsHelper
end

Codigo MVC/app/helpers/semestres_helper.rb
module SemestresHelper
end

Codigo MVC/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

Codigo MVC/app/views/alumnos/_form.html.erb
<%= form_with(model: alumno, local: true) do |form| %>
  <% if alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alumno.errors.count, "error") %> prohibited this alumno from being saved:</h2>

      <ul>
      <% alumno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.text_field :usuario_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Codigo MVC/app/views/alumnos/edit.html.erb
<h1>Editing Alumno</h1>

<%= render 'form', alumno: @alumno %>

<%= link_to 'Show', @alumno %> |
<%= link_to 'Back', alumnos_path %>

Codigo MVC/app/views/alumnos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alumnos</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alumnos.each do |alumno| %>
      <tr>
        <td><%= alumno.usuario %></td>
        <td><%= link_to 'Show', alumno %></td>
        <td><%= link_to 'Edit', edit_alumno_path(alumno) %></td>
        <td><%= link_to 'Destroy', alumno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alumno', new_alumno_path %>

Codigo MVC/app/views/alumnos/new.html.erb
<h1>New Alumno</h1>

<%= render 'form', alumno: @alumno %>

<%= link_to 'Back', alumnos_path %>

Codigo MVC/app/views/alumnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @alumno.usuario %>
</p>

<%= link_to 'Edit', edit_alumno_path(@alumno) %> |
<%= link_to 'Back', alumnos_path %>

Codigo MVC/app/views/aulas/_form.html.erb
<%= form_with(model: aula, local: true) do |form| %>
  <% if aula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aula.errors.count, "error") %> prohibited this aula from being saved:</h2>

      <ul>
      <% aula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :numero %>
    <%= form.number_field :numero %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :horario_id %>
    <%= form.text_field :horario_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Codigo MVC/app/views/aulas/edit.html.erb
<h1>Editing Aula</h1>

<%= render 'form', aula: @aula %>

<%= link_to 'Show', @aula %> |
<%= link_to 'Back', aulas_path %>

Codigo MVC/app/views/aulas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Aulas</h1>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Nombre</th>
      <th>Horario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aulas.each do |aula| %>
      <tr>
        <td><%= aula.numero %></td>
        <td><%= aula.nombre %></td>
        <td><%= aula.horario %></td>
        <td><%= link_to 'Show', aula %></td>
        <td><%= link_to 'Edit', edit_aula_path(aula) %></td>
        <td><%= link_to 'Destroy', aula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aula', new_aula_path %>

Codigo MVC/app/views/aulas/new.html.erb
<h1>New Aula</h1>

<%= render 'form', aula: @aula %>

<%= link_to 'Back', aulas_path %>

Codigo MVC/app/views/aulas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @aula.numero %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @aula.nombre %>
</p>

<p>
  <strong>Horario:</strong>
  <%= @aula.horario %>
</p>

<%= link_to 'Edit', edit_aula_path(@aula) %> |
<%= link_to 'Back', aulas_path %>